[package]
name = "app-component-operator-email-reader"
edition = "2021"
version = "0.0.1"
license = "GPL-3.0-or-later"
authors = ["Layer Labs (Cayman)"]
repository = "https://github.com/Lay3rLabs/telegram-payments.git"
rust-version = "1.90.0"

[lib]
crate-type = ["cdylib"]

[dependencies]

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# WAVS
wavs-wasi-utils = { workspace = true }
wavs-types = { workspace = true, default-features = false, features = [
  "cosmwasm",
] }

# WASI
wstd = { workspace = true }
wit-bindgen-rt = { workspace = true }
wit-bindgen = { workspace = true }
wasip2 = { workspace = true }

# Serialization
serde = { workspace = true}
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }

# Async
futures = { workspace = true }

# Email
imap = { workspace = true, default-features = false }
mailparse = { workspace = true }
cfdkim = { workspace = true}

# Security
zeroize = { workspace = true }

# Misc
cfg-if = { workspace = true }

# Logging
sloggers = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
