[package]
name = "task-helper"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
app-contract-api = { workspace = true }
app-utils = { workspace = true }
app-client = { workspace = true, features = ["binary"] }
tokio = {workspace = true}
clap = {workspace = true}
dotenvy = {workspace = true}
rand = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
anyhow = {workspace = true}
wavs-types = {workspace = true}
rustls = {workspace = true}
tracing = {workspace = true}
layer-climb = {workspace = true}
reqwest = {workspace = true}
cosmwasm-std = {workspace = true}
const-hex = {workspace = true}
