[package]
name = "app-contract-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wavs-types = { workspace = true }
cosmwasm-std = {workspace = true}
anyhow = {workspace = true}
cosmwasm-schema = {workspace = true}
serde = {workspace = true}
cw-storage-macro = {workspace = true}
cw-storage-plus = {workspace = true}
sha2 = {workspace = true}
const-hex = {workspace = true}
mailparse = {workspace = true}
