[default]
jaeger = "http://localhost:4317"
prometheus = "http://localhost:9092"

[default.chains.cosmos.pion-1]
bech32_prefix = "neutron"
rpc_endpoint = "https://rpc-lb-pion.ntrn.tech"
grpc_endpoint = "http://grpc-lb-pion.ntrn.tech:80"
gas_price = 0.0053
gas_denom = "untrn"

[default.chains.cosmos.neutron-1]
bech32_prefix = "neutron"
rpc_endpoint = "https://rpc-lb.neutron.org"
grpc_endpoint = "http://grpc-lb.neutron.org:80"
gas_price = 0.0053
gas_denom = "untrn"

[default.chains.dev.local]
type = "cosmos"
chain_id = "pion-1"
bech32_prefix = "neutron"
rpc_endpoint = "http://localhost:26657"
grpc_endpoint = "http://localhost:9090"
gas_price = 0.025
gas_denom = "untrn"

[wavs]

[cli]

[aggregator]
