[package]
name = "app-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app-contract-api = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
cosmwasm-std = { workspace = true }
layer-climb = { workspace = true }
tracing = {workspace = true}
cfg-if = {workspace = true}
tracing-subscriber = {workspace = true}
anyhow = {workspace = true}
wavs-types = {workspace = true}
thiserror = {workspace = true}
async-trait = {workspace = true}
toml = {workspace = true}
reqwest = {workspace = true}
tokio = {workspace = true}
deadpool = { workspace = true}
cw-multi-test = { workspace = true}
wstd = { workspace = true}
wavs-wasi-utils = { workspace = true}
